[android] Revert change to look for CGFloat in CoreFoundation from #88004 (#88051)
This broke cross-compiling Foundation on the Android
CI,
so reverting to fix CI till we can investigate more:
```
21:02:07  /source/swift-project/swift-corelibs-foundation/Sources/Foundation/NSDate.swift:33:43: error: standard library type 'CGFloat' is missing or broken; this is a compiler bug
21:02:07   31 | extension timeval {
21:02:07   32 |     internal init(_timeIntervalSince1970: TimeInterval) {
21:02:07   33 |         let (integral, fractional) = modf(_timeIntervalSince1970)
21:02:07      |                                           `- error: standard library type 'CGFloat' is missing or broken; this is a compiler bug
```